// THE DISPLAY'S OWN PAINT — the syntax colours, the active tab's underline and
// the rendered document's block hierarchy, shipped WITH the display.
//
// WHY THIS FILE EXISTS. A host builds its stylesheet by SCANNING SOURCE for
// utility classes, and this package's source is not in the trees a host scans:
// an installed package sits outside them, and a linked development clone sits in
// a path the host's own ignore rules exclude. A utility class used only here is
// therefore never generated — the class attribute is written, the element is in
// the page, and no rule exists. Nothing errors; the paint is simply absent.
//
// Three of this display's classes were absent for exactly that reason. The
// active tab's underline drew at the right height in the right place with no
// background, because the application's own tabs spell that class behind a state
// variant and the plain form was generated by nobody. The code view's two token
// colours were arbitrary-value classes no other file uses, so a code span and a
// link span inherited the body colour and the whole view read as plain text —
// in both themes.
//
// So the paint that must land lands from here: a stylesheet the package carries,
// keyed to the data attributes the display already writes.
//
// EVERY SELECTOR IS SCOPED TO THIS DISPLAY, and that is not decoration. A style
// element styles the WHOLE DOCUMENT, not the subtree it happens to sit in — so a
// rule written for the rendered document alone would have reached any element
// anywhere on the page that carried the same attribute, host or third party. The
// display's own root carries `data-artifact-renderer="markdown"`, so every rule
// below begins there and can reach nothing outside it.
//
// NO COLOUR IS WRITTEN HERE. Every one is a named application custom property —
// the same tokens the application's own components use, so this display follows
// the theme instead of carrying a palette of its own, and follows it in light
// and dark without knowing which is on. Where a token might be absent (a display
// drawn inside a third-party application that defines fewer of them), the
// fallback is `currentColor` or a neutral keyword, never an invented colour.
//
// THE SYNTAX COLOURS ARE THE STATUS PALETTE'S: indigo, mustard and sea-green —
// the three accents the application already reserves for meaning, so a heading,
// a code span and a link read as themselves rather than as decoration.

import type { ReactElement } from "react";

export const MARKDOWN_DISPLAY_CSS = `
[data-artifact-renderer="markdown"] [role="tab"] {
  position: relative;
}
[data-artifact-renderer="markdown"] [role="tab"][data-active="true"] {
  color: var(--primary, currentColor);
}
[data-artifact-renderer="markdown"] [role="tab"][data-active="true"]::after {
  content: "";
  position: absolute;
  inset-inline: 0;
  bottom: -1px;
  height: 2px;
  background: var(--primary, currentColor);
  pointer-events: none;
}

[data-artifact-renderer="markdown"] [data-token] {
  color: var(--foreground, currentColor);
}
[data-artifact-renderer="markdown"] [data-token="heading"] {
  color: var(--info, currentColor);
  font-weight: 600;
}
[data-artifact-renderer="markdown"] [data-token="code"] {
  color: var(--warning, currentColor);
}
[data-artifact-renderer="markdown"] [data-token="link"] {
  color: var(--success, currentColor);
}
[data-artifact-renderer="markdown"] [data-token="strong"] {
  font-weight: 700;
}
[data-artifact-renderer="markdown"] [data-token="emphasis"] {
  font-style: italic;
}
[data-artifact-renderer="markdown"] [data-token="marker"] {
  color: var(--muted-foreground, currentColor);
}

[data-artifact-renderer="markdown"] [data-markdown-body] > :first-child {
  margin-block-start: 0;
}
[data-artifact-renderer="markdown"] [data-markdown-body] > :last-child {
  margin-block-end: 0;
}
[data-artifact-renderer="markdown"] [data-markdown-body] h1 {
  font-size: 1.75rem;
  font-weight: 700;
  line-height: 1.2;
  letter-spacing: -0.02em;
  margin-block: 2rem 0.75rem;
}
[data-artifact-renderer="markdown"] [data-markdown-body] h2 {
  font-size: 1.375rem;
  font-weight: 650;
  line-height: 1.25;
  letter-spacing: -0.015em;
  margin-block: 1.75rem 0.625rem;
}
[data-artifact-renderer="markdown"] [data-markdown-body] h3 {
  font-size: 1.125rem;
  font-weight: 600;
  line-height: 1.3;
  margin-block: 1.5rem 0.5rem;
}
[data-artifact-renderer="markdown"] [data-markdown-body] h4,
[data-artifact-renderer="markdown"] [data-markdown-body] h5,
[data-artifact-renderer="markdown"] [data-markdown-body] h6 {
  font-size: 1rem;
  font-weight: 600;
  line-height: 1.35;
  margin-block: 1.25rem 0.5rem;
}
[data-artifact-renderer="markdown"] [data-markdown-body] p {
  margin-block: 0 1rem;
}
[data-artifact-renderer="markdown"] [data-markdown-body] ul,
[data-artifact-renderer="markdown"] [data-markdown-body] ol {
  margin-block: 0 1rem;
  padding-inline-start: 1.5rem;
}
[data-artifact-renderer="markdown"] [data-markdown-body] ul {
  list-style: disc;
}
[data-artifact-renderer="markdown"] [data-markdown-body] ol {
  list-style: decimal;
}
[data-artifact-renderer="markdown"] [data-markdown-body] li {
  margin-block: 0.25rem;
}
[data-artifact-renderer="markdown"] [data-markdown-body] li > ul,
[data-artifact-renderer="markdown"] [data-markdown-body] li > ol {
  margin-block: 0.25rem 0;
}
[data-artifact-renderer="markdown"] [data-markdown-body] blockquote {
  margin-block: 0 1rem;
  padding-inline-start: 1rem;
  border-inline-start: 2px solid var(--line, currentColor);
  color: var(--muted-foreground, currentColor);
}
[data-artifact-renderer="markdown"] [data-markdown-body] pre {
  margin-block: 0 1rem;
  padding: 0.75rem 1rem;
  border-radius: 0.5rem;
  background: var(--surface-muted, transparent);
  overflow-x: auto;
}
[data-artifact-renderer="markdown"] [data-markdown-body] code {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 0.9em;
}
[data-artifact-renderer="markdown"] [data-markdown-body] :not(pre) > code {
  padding: 0.125rem 0.375rem;
  border-radius: 0.25rem;
  background: var(--surface-muted, transparent);
}
[data-artifact-renderer="markdown"] [data-markdown-body] a {
  color: var(--info, currentColor);
  text-decoration: underline;
  text-underline-offset: 2px;
}
[data-artifact-renderer="markdown"] [data-markdown-body] strong {
  font-weight: 650;
}
[data-artifact-renderer="markdown"] [data-markdown-body] hr {
  margin-block: 1.5rem;
  border: 0;
  border-block-start: 1px solid var(--line, currentColor);
}
[data-artifact-renderer="markdown"] [data-markdown-body] table {
  margin-block: 0 1rem;
  border-collapse: collapse;
  display: block;
  overflow-x: auto;
}
[data-artifact-renderer="markdown"] [data-markdown-body] th,
[data-artifact-renderer="markdown"] [data-markdown-body] td {
  padding: 0.375rem 0.625rem;
  border: 1px solid var(--line, currentColor);
  text-align: start;
}
[data-artifact-renderer="markdown"] [data-markdown-body] th {
  font-weight: 600;
}
[data-artifact-renderer="markdown"] [data-markdown-body] img {
  max-width: 100%;
  height: auto;
}
`;

/**
 * The stylesheet, mounted with the display.
 *
 * Drawn inside the display's own element rather than hoisted to the document, so
 * a host that mounts one display, ten displays or none carries exactly the rules
 * its page needs and nothing outlives the component.
 *
 * ONCE PER DISPLAY. Each display root mounts this exactly once and the parts
 * beneath it never mount it again — a Preview that carried its own copy would
 * have turned one style element into two the moment a tab was pressed, and into
 * more again for every display on the page. The rules are identical wherever
 * they appear, so several displays on one page are correct either way; the
 * single mount is what keeps the page's style nodes proportional to the displays
 * drawn rather than to the tabs pressed.
 */
export function MarkdownDisplayStyle(): ReactElement {
  return <style>{MARKDOWN_DISPLAY_CSS}</style>;
}
